all:
	cd e1000/e1000-7.3.21/src; make
	cd e1000/e1000-8.0.16/src; make
	cd e1000e/e1000e-1.0.15/src; make
	cd e1000e/e1000e-1.2.17/src; make
	cd igb/igb-2.0.6/src; make
	cd ixgbe/ixgbe-2.0.44.14-No-FlowDirector/src; make
	cd ixgbe/ixgbe-2.1.4-FlowDirector-NoTNAPI/src; make